/* SPDX-License-Identifier: GPL-2.0-or-later */
#pragma once

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#define RGB_TRIGGER_ON_KEYDOWN
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_STARLIGHT_DUAL_HUE
#define RGB_MATRIX_DEFAULT_VAL 200
#define RGB_MATRIX_DEFAULT_SPD 64

#define TAPPING_TERM 220
#define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_TERM_PER_KEY
